Sprint #10
Noskovsk/java-filmorate pull request #1
Opened 2022-08-08 10:10 UTC by Noskovsk

2022-08-09 09:06 UTC, Frilock requested changes
Добрый день, оставил ряд комментариев к работе, будут вопросы пишите в Slack.

2022-08-09 09:06 UTC, Frilock commented on pom.xml
> +			<version>1.18.20</version>
Версии библиотек, которые вы подключаете в pom файле, принято указывать в properties, по аналогии с версией Java, а в поле version самой библиотеки указывать так ${simple-lib.version}. Это нужно для того, чтобы версии библиотек находились в одном месте и их изменении проходило безболезненно.

2022-08-09 09:06 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +		System.out.println("start");
В консоли и так увидите, что стартануло приложение.

2022-08-09 09:06 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotEmpty
А эти аннотации друг друга не дублируют? Чем NotEmpty отличается от NonNull?

2022-08-09 09:06 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public void additionalValidation() {
Предлагаю данный метод вынести в контроллер, поскольку в классах модели не принято делать такие проверки

2022-08-09 09:06 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    public void normalaize() {
Аналогично

2022-08-09 09:06 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private String name = "";
А зачем = "" ?

2022-08-09 09:06 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +public class ValidationException extends RuntimeException{
Пробел после RuntimeEception

2022-08-09 09:06 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/exception/UnknownObjectException.java
> +public class UnknownObjectException extends RuntimeException{
Пробел после RuntimeEception

2022-08-09 09:06 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @GetMapping("/users")
Чтобы над каждым методом не писать маппинг с "/users", вы можете повесить аннотацию на контроллер, по моему RequestMapping("/users")

2022-08-11 10:39 UTC, Frilock requested changes
Добрый день, еще пара комментариев к работе.

2022-08-11 10:39 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping("/films")
А почему в итоге не хотите на контроллер повесить @RequestMapping("/films") ?
Чтобы над каждым методом ("/films") не добавлять

2022-08-11 10:39 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    }
Пустая строка после метода

2022-08-11 10:39 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public static void normalaizeUser(User user) {
А зачем метод делать публичным? Вы его только в данном классе используете вроде.
Кроме того зачем его делать статичным?

2022-08-11 10:39 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public static void additionalFilmValidation(Film film) {
А зачем метод делать публичным? Вы его только в данном классе используете вроде.
Кроме того зачем его делать статичным?

2022-08-11 10:39 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @Pattern(regexp = "^\\S*$", message = "Ошибка. В Логине не должно содержаться пробелов!")
Если у Вас проверяется регулярным выражением данные, то зачем нужны все 3 аннотации выше?
Одна из них проверяет на != null, другая != "", а третья я так понимаю на != "  ".

2022-08-12 09:15 UTC, Frilock approved these changes
Работу принял, но написал несколько комментариев, учтите при следующей итерации

2022-08-12 09:15 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@Slf4j
Лишняя аннотация

2022-08-12 09:15 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +@Slf4j
Лишняя аннотация

2022-08-12 09:15 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.warn("Дата релиза у фильма: {} должна быть больше 28 декабря 1895 года.", film.getReleaseDate());
а почему warn если вы ошибку бросаете. В лог тоже error логичнее логгировать

2022-08-12 09:15 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.warn("Фильм :{}, не найден в библиотеке!", film);
Тут тоже

2022-08-12 09:15 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private Map<Long, Film> films = new HashMap<>();
можно final

2022-08-12 09:15 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private Map<Long, User> users = new HashMap();
можно final

2022-08-12 09:15 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private void normalaizeUser(User user) {
normalize по идее так

2022-08-12 09:15 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +public class FilmController {
Вообще у контроллеров довольно много общего, по этому можно было абстрактный класс сделать и общие методы туда перенести

2022-08-19 10:32 UTC, closed without merging

2022-08-19 10:33 UTC, Noskovsk commented
Спринт завершен